Update nf-winsock2-wsaenumnamespaceprovidersa.md
Make the example compile. The error from 'cl' was:
```
error C2440: 'function': cannot convert from 'GUID' to 'const GUID *const '
warning C4024: 'StringFromGUID2': different types for formal and actual parameter 1
```